const challenge = {
    truths : [
      "Quelle est la dernière chose que vous avez recherchée sur votre téléphone ?",
      "Qui est, selon vous, la personne la plus mal habillée dans cette pièce ?",
      "Quand avez-vous volé pour la dernière fois ?",
      "Vous êtes-vous déjà entraîné à embrasser devant un miroir ?",
      "Qui est ton préféré ? Maman ou Papa ?",
      "Si quelqu'un vous offrait 1 million de dollars pour rompre avec votre petite amie/petit ami, le feriez-vous ?",
      "Si vous pouviez remonter le temps et effacer une chose que vous avez dite ou faite, quelle serait-elle ?",
      "Si vous pouviez soudainement devenir invisible, que feriez-vous ?",
      "Quelle est la personne que vous prétendez aimer, mais que vous n'aimez pas ?",
      "Quand avez-vous mouillé votre lit pour la dernière fois ?",
      "Avez-vous déjà mangé quelque chose sur le sol ?",
      "Qui était votre premier baiser ? As-tu aimé ça ?",
      "Quelle est la chose la plus sexy chez un homme ?",
      "Si vous pouviez sortir avec une célébrité, qui ce serait ?",
      "Décrivez la carrière de vos rêves.",
      "Si vous pouviez manger tout ce que vous voulez sans grossir, quel serait cet aliment ?",
      "Si vous deviez faire un jeu télévisé avec quelqu'un dans cette pièce, qui choisiriez-vous ?",
      "Passeriez-vous un an sans votre téléphone si cela vous permettait d'épouser la personne de vos rêves ?",
      "Qui détesteriez-vous voir nu ?",
      "Combien de temps êtes-vous resté sans prendre de douche ?",
      "Si vous ne pouviez envoyer qu'un seul texto à une personne pour le reste de votre vie, mais que vous ne pouviez jamais lui parler en face à face, qui serait-ce ?",
      "Combien de temps êtes-vous resté sans vous brosser les dents ?",
      "Quelle est la chose que vous ne mangeriez jamais à un premier rendez-vous ?",
      "Qu'avez-vous vu que vous aimeriez ne plus voir ?",
      "Si vous pouviez vous réincarner dans le corps de n'importe qui, qui voudriez-vous devenir ?",
      "Si vous changiez de sexe pour la journée, que feriez-vous ?",
      "Quel est l'aliment que vous ne commanderez jamais dans un restaurant ?",
      "Quel est le pire temps pour être coincé dehors si tout ce que vous pouvez porter est un maillot de bain ?",
      "Si votre voiture tombait en panne au milieu de la route, qui dans cette pièce serait la dernière personne que vous appelleriez ? Pourquoi ?",
      "Quelle est la connaissance la plus inutile que vous connaissiez ?",
      "Qu'avez-vous appris à l'école que vous aimeriez pouvoir oublier ?",
      "Quel animal ressemble le plus à votre façon de manger ?",
      "Si vous pouviez choisir de ne jamais transpirer pour le reste de votre vie ou de ne jamais avoir à aller aux toilettes, que choisiriez-vous ?",
      "Si vous pouviez passer chaque instant avec votre petit(e) ami(e), le feriez-vous ?",
      "S'il vous restait un jour à vivre, que feriez-vous en premier ?",
      "Es-tu déjà sorti avec quelqu'un alors que tu étais encore amoureux de quelqu'un d'autre ?",
      "Notez tout le monde dans la pièce de 1 à 10, 10 étant la meilleure personnalité.",
      "Si vous pouviez échanger une caractéristique physique avec votre meilleur ami, quelle serait-elle ?",
      "Avez-vous déjà dit un secret que l'on vous a demandé de garder ?",
      "Avec combien de personnes une personne peut-elle coucher avant que vous ne la jugiez secrètement pour son 'numéro' ?",
      "Penses-tu que le petit ami/la petite amie de ton ami(e) est sexy ? Est-ce que tu coucherais avec lui/elle si tu savais qu'il/elle ne le découvrirait jamais ?",
      "Jusqu'où iriez-vous pour un premier rendez-vous ?",
      "Avez-vous déjà regretté quelque chose que vous avez fait pour attirer l'attention d'un(e) amoureux(se) ?",
      "Si tu n'as pas encore eu ton premier baiser, avec qui dans cette pièce veux-tu avoir ton premier baiser ?",
      "Quelle activité sexuelle considérez-vous comme totalement hors limites ?",
      "Si vous n'aviez que 24 heures à vivre et que vous pouviez faire n'importe quoi avec n'importe qui dans cette pièce, qui cela serait-il et que feriez-vous avec cette personne ?",
      "Si vous deviez faire un discours de remise des diplômes dans une université, que diriez-vous aux diplômés ?",
      "Vous engageriez-vous dans une relation à distance ?",
      "Si vous pouviez changer une chose sur votre corps, quelle serait-elle ?",
      "Si l'argent n'avait pas d'importance, quel serait le job de vos rêves ?",
      "Quelle est la chose la plus bizarre que vous ayez faite devant un miroir",
      "Avez-vous déjà volé quelque chose ?",
      "Avez-vous laissé quelqu'un d'autre porter le chapeau pour quelque chose que vous avez fait ?",
      "Quel était votre surnom d'enfance ?"
    ],
    dares : [
      "Prenez un selfie embarrassante et postez-la comme photo de profil",
      "Remplissez votre bouche d'eau, et chaque personne du groupe doit raconter la blague la plus drôle qu'elle connaisse. Si vous recrachez l'eau, vous devez manger une cuillerée de terre.",
      "Jusqu'au prochain tour, parlez super fort, comme si personne ne pouvait vous entendre.",
      "Riez comme un fou",
      "Lèche le dessous de ta chaussure",
      "Laissez le groupe vous faire poser dans une position embarrassante et prendre une photo.",
      "Laissez le groupe regarder votre téléphone pendant 2 minutes.",
      "Parlez avec un accent étrange pour le reste de la nuit.",
      "Appelez le 7ème contact de votre téléphone et chantez-lui 30 secondes d'une chanson choisie par le groupe.",
      "Faire un massage à un compagnon pendant 5 minutes.",
      "Parlez sans fermer la bouche.",
      "Entrez dans un débat avec un mur.",
      "Soyez l'animal de compagnie de quelqu'un pendant les 5 prochaines minutes.",
      "Essayer de faire du break dance pendant 30 secondes.",
      "Crier et jouer la première phrase qui vous vient à l'esprit",
      "Renifler les aisselles de tout le monde dans la pièce",
      "Suppliez et plaidez auprès de la personne à votre droite pour qu'elle ne vous quitte pas pour cet autre garçon ou cette autre fille. Les pleurs, les grincements de dents et les gémissements sont encouragés.",
      "Séduire un membre du même sexe dans le groupe.",
      " Allez aux toilettes, enlevez vos sous-vêtements et mettez-les sur votre tête. Portez-le sur votre tête pour le reste du jeu.",
      " Fermez les yeux et envoyez un texto à l'aveugle à une personne aléatoire ",
      "Échangez un vêtement avec le joueur à votre droite",
      "Montrez tout ce qu'il y a dans votre sac à main",
      "Allez dans la pièce d'à côté et demandez des bananes à votre voisin",
      " Lécher le pied de quelqu'un 2 fois",
      "Regarder dans les yeux d'une fille ou d'un garçon pendant 30 secondes",
      "Danser un slow sur une chanson rapide.",
      "Sautiller comme un kangourou pendant une minute et couvrir toute la pièce.",
      "Envoyez un SMS à votre amis, en leur disant que vos pieds sentent généralement la tomate pourrie et demandez s'ils supporteraient cela",
      "Racontez en détail au groupe votre premier baiser.",
      "Révéler la couleur de votre caleçon/culotte.",
      "Faites des allers-retours sous la table jusqu'à ce que ce soit à nouveau votre tour.",
      "Appelez 5 personnes différentes et parlez-leur avec 5 accents différents.",
      "Boire 3 grandes tasses d'eau sans s'arrêter.",
      "Dites à votre petite amie/petit ami que vos amis ne l'aiment pas et que vous ne pouvez plus être avec elle/il."
    ]
  };
  